//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMart.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public int AdminId { get; set; }
        public string AdminName { get; set; }
        public string AdminAddress { get; set; }
        public string AspId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
